// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public abstract class Action {
	/**
	 * 
	 */
	protected String actionExplanation;
	/**
	 * 
	 */
	private Game gameInstance;
	/**
	 * 
	 */
	private Player currentPlayer;

	/**
	 * 
	 * @param game 
	 * @param player 
	 */
	public void execute(Game game, Player player) {
	}
}
