// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Abstract class reprsenting an action a player can take 
 */
public abstract class Action {
	protected String actionExplanation; // Explains what the action is 

	/**
	 * Returns a string explaining what the action is
	 * @return value of actionExplanation attribute
	 */
	public String getActionExplanation() {
		return actionExplanation;
	}

	/**
	 * Execute the action - implementation defined in subclasses
	 * @param game Game instance 
	 * @param player Player which action is being performed by
	 */
	public abstract void execute(Game game, Player player);
}
