// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Edge[] edges;

	/**
	 * 
	 */
	public void initializeMap() {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Tile getTileById(Integer id) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Node getNodeById(Integer id) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Edge getEdgeById(Integer id) {
	}
}
