// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public abstract class Building {
	/**
	 * 
	 */
	private Player owner; 
	/**
	 * 
	 */
	private Node location;

	public Building(Player owner, Node location) {
		this.owner = owner;
		this.location = location;
		location.addBuilding(this);
	}

	/**
	 * 
	 * @return 
	 */
	public abstract int getVictoryPoints();

	/**
	 * 
	 * @return 
	 */
	public Node getLocation() {
		return location;
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
		return owner;
	}
}
