// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class City extends Building {
	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
		return 2; // Cities are worth 2 victory points 
	}
}
