// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Config {
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	private Game game;

	/**
	 * 
	 */
	public void load() {
	}
}
