// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Road road;
	/**
	 * 
	 */
	private Node first;
	/**
	 * 
	 */
	private Node second;

	/**
	 * Checksi if edge is occupied by a road
	 * @return occupied status of edge
	 */
	public boolean edgeOccupied() {
		return road != null; 
	}

	/**
	 */
	public void addRoad() {
	}
}
