// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Road road = null;
	/**
	 * 
	 */
	private Node first;
	/**
	 * 
	 */
	private Node second;

	public Edge(int id, Node first, Node second) {
		this.id = id; 
		this.first = first;
		this.second = second; 
	}

	/**
	 * Check is if edge is occupied by a road
	 * @return occupied status of edge
	 */
	public boolean edgeOccupied() {
		return road != null; 
	}

	public Node getFirst() {
		return first;
	}

	public Node getSecond() {
		return second;
	}

	/**
	 */
	public void addRoad(Road road) {
		if(edgeOccupied()) {
			throw new IllegalStateException("Edge already occupied by a road");
		}
		this.road = road;
	}
}
