// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private int currentRound;
	/**
	 * 
	 */
	private boolean gameFinished;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private Dice dice;

	/**
	 * 
	 */
	public void start() {
		board.initializeMap();

		while (!gameFinished) {
			playRound();
			printRoundSummary();
			gameFinished = checkTerminationCondition();
		}
	}

	/**
	 * 
	 */
	public void playRound() {
		currentRound = currentRound+1;

		for (Player player: players) {
			int resultDice = dice.roll();
			resourceDistributor(resultDice);
			player.takeTurn(this);
		}
	}

	public void resourceDistributor(int rollResult) {
		List<ResourceDistribution> distribution = getPlayersOnTile(rollResult);

		for (ResourceDistribution input: distribution) {
			Player player = input.getPlayer();
			ResourceHand resourceHand = player.getResourceHand();
			resourceHand.add(input.getResourceType(), input.getNumberOfCardsToGive());
		}
	}

	public List<ResourceDistribution> getPlayersOnTile(int rollResult) {
		List<ResourceDistribution> distribution = new ArrayList<>();
		List<Tile> sameTokenNumberTiles = new ArrayList<>();


		sameTokenNumberTiles = board.getTilesByToken(rollResult);

		for (Tile tile: sameTokenNumberTiles){
			Node[] adjacentNodes = tile.getAdjacentNodes();
			ResourceType resourceType = tile.getResourceType();
			if (resourceType == null) { //this should account for if the tile is not meant to give out resources
				continue;
			}

			for (Node node: adjacentNodes){
				Building building = node.getBuilding();
				if (building == null) {
					continue;
				}

				int numberOfCardsToGive;
				if (building instanceof Settlement) {
					numberOfCardsToGive = 1;
				}
				else if (building instanceof City) {
					numberOfCardsToGive = 2;
				} else {
					continue;
				}
				
				Player owner = building.getOwner();
				distribution.add(new ResourceDistribution(owner, numberOfCardsToGive, resourceType));
			}
		}
		
		return distribution;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean checkTerminationCondition() {
		for (Player player: players) {
			if (player.getVictoryPoints()>=10) {
				return true;
			}
		}
		return false;
	}

	/**
	 * 
	 */
	public void printRoundSummary() {
		System.out.println("Current Round: " + this.currentRound);
		for (Player player: players) {
			System.out.println("Player id: " + player.getId() + " Player Hand: " + player.getResourceHand() + " Player Victory Points: " + player.getVictoryPoints());
		}
	}

	/**
	 * 
	 * @param board 
	 * @param players 
	 * @param dice 
	 */
	public Game(Board board, Player[] players, Dice dice) {

		if (board==null || players==null || dice==null || players.length<2 || players.length>4){
			throw new IllegalArgumentException("Error: One or more of the objects given are null");
		}

		this.board = board;
		this.players = players;
		this.dice = dice;

		this.currentRound = 0;
		this.gameFinished = false;
	}
}
