// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private Integer currentRound;
	/**
	 * 
	 */
	private Integer maxRounds;
	/**
	 * 
	 */
	private Boolean gameFinished;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private Dice dice;

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void playRound() {
	}

	/**
	 * 
	 * @return 
	 */
	public Boolean checkTerminationCondition() {
	}

	/**
	 * 
	 */
	public void printRoundSummary() {
	}

	/**
	 * 
	 * @param board 
	 * @param players 
	 * @param dice 
	 */
	public void Game(Board board, Player[] players, Dice dice) {
	}
}
