// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Building building;
	/**
	 * 
	 */
	private Node[] adjacentNodes;

	/**
	 * Checks if node is occupied by a building
	 * @return occupied status of node
	 */
	public boolean nodeOccupied() {
		return building != null;
	}

	public Building getBuilding() {
		return building;
	}

	/**
	 * 
	 * @param building 
	 */
	public void addBuilding(Building building) {
		this.building = building;
	}
}
