// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private Integer id;
	/**
	 * 
	 */
	private Building building;
	/**
	 * 
	 */
	private Node[] adjacentNodes;

	/**
	 * 
	 * @return 
	 */
	public Boolean nodeOccupied() {
	}

	/**
	 * 
	 * @param building 
	 */
	public void addBuilding(Building building) {
	}
}
