// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Pass extends Action {
	/**
	 * 
	 * @param game 
	 * @param player 
	 */
	public void execute(Game game, Player player) {
	}
}
