// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
class Player {
	/**
	 * 
	 */
	private Integer id;
	/**
	 * 
	 */
	private Integer victoryPoints;
	/**
	 * 
	 */
	private ResourceHand hand;
	/**
	 * 
	 */
	private Building[] buildings;
	/**
	 * 
	 */
	private Road[] roads;
	/**
	 * 
	 */
	private Agent agent;

	/**
	 * 
	 * @param game 
	 */
	public void takeTurn(Game game) {
	}

	/**
	 * 
	 * @param amount 
	 */
	public void collectPoints(Integer amount) {
	}

	/**
	 * 
	 * @param building 
	 */
	public void addBuilding(Building building) {
	}

	/**
	 * 
	 * @param building 
	 */
	public void deleteBuilding(Building building) {
	}

	/**
	 * 
	 * @param road 
	 */
	public void addRoad(Road road) {
	}
}
