// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class ResourceHand {
	/**
	 * 
	 */
	private Player owner;

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void add(ResourceType type, Integer amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void remove(ResourceType type, Integer amount) {
	}

	/**
	 * 
	 * @return 
	 */
	public Integer totalCards() {
	}
}
