// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public enum ResourceType {
	WOOD,
	BRICK,
	SHEEP,
	WHEAT,
	ORE;
}
