// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Edge location;

	/**
	 * 
	 * @return 
	 */
	public Edge getRoadLocation() {
	}
}
