// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Edge location;

	/**
	 * 
	 * @return 
	 */
	public Edge getRoadLocation() {
		return location;
	}

	public Road(Player owner, Edge location) {
		this.owner = owner;
		this.location = location;
		location.addRoad(this);
	}
}
